name: Deploy docker image to Production

on: 
  workflow_dispatch:
    inputs:
      sha:
        description: 'Image version (SHA)'     
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          project_id:  ${{ secrets.GOOGLE_PROJECT_ID }}
          export_default_credentials: true
        
      - name: Deploy to Google Cloud Run
        run: |
            gcloud run deploy fitfinderserviceprod \
              --image asia.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/fitfinderservice:${{ github.event.inputs.sha }} \
              --platform managed \
              --region australia-southeast1