name: Build/Deploy to Cloud Run (Staging)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build .NET Core solution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code base
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: .NET Build
      run: dotnet build --configuration Release --no-restore
      
    - name: .NET Test
      run: dotnet test --no-restore --verbosity normal
  
  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy to Cloud Run (Staging)
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
        
      - name: Setup Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          project_id:  ${{ secrets.GOOGLE_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Login to Docker (Google Cloud)
        run: gcloud auth configure-docker
        
      - name: Build Docker Image
        run: |
            docker build \
              -f FitFinder.Grpc/Dockerfile \
              -t asia.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/fitfinderservice:${GITHUB_SHA} \
              -t asia.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/fitfinderservice:latest \
              -t ghcr.io/davidngjy/fitfinderservice:${GITHUB_SHA} \
              -t ghcr.io/davidngjy/fitfinderservice:latest \
              .
        
      - name: Push to Google Container Registry
        run: docker push asia.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/fitfinderservice
        
      - name: Deploy to Google Cloud Run (Staging container)
        run: |
            gcloud run deploy fitfinderservicestaging \
              --image asia.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/fitfinderservice:${GITHUB_SHA} \
              --platform managed \
              --region australia-southeast1

      - name: Login to Docker (GitHub)
        run: docker login ghcr.io -u davidngjy --password ${{ secrets.PACKAGE_CREDENTIAL }}

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/davidngjy/fitfinderservice
